audio:
  chunk_size: 485100
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 0.001

model:
  in_channels: 2
  sources: 2
  freq_bins: 2049
  embed_dim: 512
  depth: 8
  dim_head: 64
  heads: 8
  ff_mult: 4
  conv_expansion_factor: 2
  conv_kernel_size: 31
  attn_dropout: 0.1
  ff_dropout: 0.1,
  conv_dropout: 0.1

training:
  batch_size: 10
  gradient_accumulation_steps: 1
  grad_clip: 0
  instruments:
  - saxophone
  - other
  lr: 5.0e-05
  patience: 2
  reduce_factor: 0.95
  target_instrument: null
  num_epochs: 1000
  num_steps: 1000
  q: 0.95
  coarse_loss_clip: true
  ema_momentum: 0.999
  optimizer: adam
  other_fix: false # it's needed for checking on multisong dataset if other is actually instrumental
  use_amp: true # enable or disable usage of mixed precision (float16) - usually it must be true

stft:
    n_fft: 4096
    hop_length: 1024
    win_length: 4096
    center: true

augmentations:
  enable: false # enable or disable all augmentations (to fast disable if needed)


inference:
  batch_size: 1
  num_overlap: 4